### ISSUE TITLE
Use `sass_builder` package

### ISSUE THREAD

**Issue by simolus3** [simolus3/zap#1]
Once the `sass_builder` package supports emitting source maps, we can use it to compile sass stylesheets instead of `zap_dev` containing yet another builder for Sass.

**Comment by vanlooverenkoen** [comment]
Looks like the source maps are generated since 2.2.0

**Comment by simolus3** [comment]
We're now using the `sass_builder` package in favor of the one that used to be included in `zap_dev`.
